import type { Metadata } from "next";
import "./globals.css";
import CustomProviders from "./providers";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <CustomProviders>
          {children}
          <Toaster position="top-right" />
        </CustomProviders>
      </body>
    </html>
  );
}
