import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "../components/Sidebar/app-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {/* <SidebarProvider> */}
        {/* <AppSidebar /> */}
        <Providers>
          {/* <SidebarTrigger /> */}
          {children}
        </Providers>
        {/* </SidebarProvider> */}
      </body>
    </html>
  );
}
